/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/config/apikeys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiKeyResponse"][];
                        "application/json": components["schemas"]["ApiKeyResponse"][];
                        "text/json": components["schemas"]["ApiKeyResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateApiKeyRequest"];
                    "text/json": components["schemas"]["CreateApiKeyRequest"];
                    "application/*+json": components["schemas"]["CreateApiKeyRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreatedApiKeyResponse"];
                        "application/json": components["schemas"]["CreatedApiKeyResponse"];
                        "text/json": components["schemas"]["CreatedApiKeyResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/apikeys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange admin credentials for a short-lived session token. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LoginResponse"];
                        "application/json": components["schemas"]["LoginResponse"];
                        "text/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The identity behind the presented bearer token (machine or admin). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MeResponse"];
                        "application/json": components["schemas"]["MeResponse"];
                        "text/json": components["schemas"]["MeResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change the signed-in admin's password. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ChangePasswordRequest"];
                    "text/json": components["schemas"]["ChangePasswordRequest"];
                    "application/*+json": components["schemas"]["ChangePasswordRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/caps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CapsResponse"];
                        "application/json": components["schemas"]["CapsResponse"];
                        "text/json": components["schemas"]["CapsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["EventRequest"];
                    "text/json": components["schemas"]["EventRequest"];
                    "application/*+json": components["schemas"]["EventRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/general": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GeneralConfigResponse"];
                        "application/json": components["schemas"]["GeneralConfigResponse"];
                        "text/json": components["schemas"]["GeneralConfigResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["GeneralConfigWrite"];
                    "text/json": components["schemas"]["GeneralConfigWrite"];
                    "application/*+json": components["schemas"]["GeneralConfigWrite"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GeneralConfigResponse"];
                        "application/json": components["schemas"]["GeneralConfigResponse"];
                        "text/json": components["schemas"]["GeneralConfigResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    deep?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["HealthResponse"];
                        "application/json": components["schemas"]["HealthResponse"];
                        "text/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/indexers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["IndexerResponse"][];
                        "application/json": components["schemas"]["IndexerResponse"][];
                        "text/json": components["schemas"]["IndexerResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["IndexerWrite"];
                    "text/json": components["schemas"]["IndexerWrite"];
                    "application/*+json": components["schemas"]["IndexerWrite"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["IndexerResponse"];
                        "application/json": components["schemas"]["IndexerResponse"];
                        "text/json": components["schemas"]["IndexerResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/indexers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["IndexerResponse"];
                        "application/json": components["schemas"]["IndexerResponse"];
                        "text/json": components["schemas"]["IndexerResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["IndexerWrite"];
                    "text/json": components["schemas"]["IndexerWrite"];
                    "application/*+json": components["schemas"]["IndexerWrite"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["IndexerResponse"];
                        "application/json": components["schemas"]["IndexerResponse"];
                        "text/json": components["schemas"]["IndexerResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/indexers/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run a `t=caps` roundtrip against the stored indexer, reporting latency. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["IndexerTestResult"];
                        "application/json": components["schemas"]["IndexerTestResult"];
                        "text/json": components["schemas"]["IndexerTestResult"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["QualityProfile"][];
                        "application/json": components["schemas"]["QualityProfile"][];
                        "text/json": components["schemas"]["QualityProfile"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["QualityProfile"];
                    "text/json": components["schemas"]["QualityProfile"];
                    "application/*+json": components["schemas"]["QualityProfile"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["QualityProfile"];
                        "application/json": components["schemas"]["QualityProfile"];
                        "text/json": components["schemas"]["QualityProfile"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/profiles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["QualityProfile"];
                        "application/json": components["schemas"]["QualityProfile"];
                        "text/json": components["schemas"]["QualityProfile"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["QualityProfile"];
                    "text/json": components["schemas"]["QualityProfile"];
                    "application/*+json": components["schemas"]["QualityProfile"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["QualityProfile"];
                        "application/json": components["schemas"]["QualityProfile"];
                        "text/json": components["schemas"]["QualityProfile"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProviderResponse"][];
                        "application/json": components["schemas"]["ProviderResponse"][];
                        "text/json": components["schemas"]["ProviderResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ProviderWrite"];
                    "text/json": components["schemas"]["ProviderWrite"];
                    "application/*+json": components["schemas"]["ProviderWrite"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProviderResponse"];
                        "application/json": components["schemas"]["ProviderResponse"];
                        "text/json": components["schemas"]["ProviderResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/providers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProviderResponse"];
                        "application/json": components["schemas"]["ProviderResponse"];
                        "text/json": components["schemas"]["ProviderResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ProviderWrite"];
                    "text/json": components["schemas"]["ProviderWrite"];
                    "application/*+json": components["schemas"]["ProviderWrite"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProviderResponse"];
                        "application/json": components["schemas"]["ProviderResponse"];
                        "text/json": components["schemas"]["ProviderResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/providers/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Connect + AUTHINFO against the stored provider; report achievable connections. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProviderTestResult"];
                        "application/json": components["schemas"]["ProviderTestResult"];
                        "text/json": components["schemas"]["ProviderTestResult"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ResolveRequest"];
                    "text/json": components["schemas"]["ResolveRequest"];
                    "application/*+json": components["schemas"]["ResolveRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResolveResponse"];
                        "application/json": components["schemas"]["ResolveResponse"];
                        "text/json": components["schemas"]["ResolveResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unprocessable Content */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Bad Gateway */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    q?: string;
                    type?: string;
                    season?: number;
                    episode?: number;
                    imdbId?: string;
                    tmdbId?: number;
                    profileId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SearchResponse"];
                        "application/json": components["schemas"]["SearchResponse"];
                        "text/json": components["schemas"]["SearchResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/debug/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["DebugSearchRequest"];
                    "text/json": components["schemas"]["DebugSearchRequest"];
                    "application/*+json": components["schemas"]["DebugSearchRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DebugSearchResponse"];
                        "application/json": components["schemas"]["DebugSearchResponse"];
                        "text/json": components["schemas"]["DebugSearchResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SessionResponse"][];
                        "application/json": components["schemas"]["SessionResponse"][];
                        "text/json": components["schemas"]["SessionResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{token}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stream/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Partial Content */
                206: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiKeyResponse: {
            id: string | null;
            name: string | null;
            prefix: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            revokedAt?: string | null;
            revoked?: boolean;
        };
        CapsCategory: {
            /** Format: int32 */
            id: number;
            name: string | null;
        };
        CapsProvider: {
            name: string | null;
            /** Format: int32 */
            priority?: number;
            enabled?: boolean;
            backupOnly?: boolean;
        };
        CapsResponse: {
            mediaTypes?: string[] | null;
            categories?: components["schemas"]["CapsCategory"][] | null;
            providers?: components["schemas"]["CapsProvider"][] | null;
        };
        /** @description Body of POST /api/v1/auth/password — admin self-service password change. */
        ChangePasswordRequest: {
            currentPassword?: string | null;
            newPassword?: string | null;
        };
        CreateApiKeyRequest: {
            name: string | null;
        };
        /** @description Returned once when a key is minted; carries the one-time plaintext token. */
        CreatedApiKeyResponse: {
            id: string | null;
            name: string | null;
            token: string | null;
        };
        DebugReleaseDto: {
            releaseId: string | null;
            title: string | null;
            indexer: string | null;
            /** Format: int64 */
            sizeBytes?: number;
            /** Format: int32 */
            ageDays?: number;
            /** Format: int32 */
            grabs?: number;
            /** Format: int32 */
            score?: number;
            rejected?: boolean;
            health: string | null;
            parsed: components["schemas"]["ParsedFieldsDto"];
            scoreBreakdown: components["schemas"]["ScoreLineDto"][] | null;
            rejections: components["schemas"]["RejectionDto"][] | null;
        };
        /** @description Request body of POST /api/v1/debug/search (BRIEF §6.2). Mirrors the /search params. */
        DebugSearchRequest: {
            q: string | null;
            type?: string | null;
            /** Format: int32 */
            season?: number | null;
            /** Format: int32 */
            episode?: number | null;
            imdbId?: string | null;
            /** Format: int32 */
            tmdbId?: number | null;
            profileId?: string | null;
        };
        /**
         * @description Response of POST /api/v1/debug/search: every release including rejected ones, with
         *     parsed fields, per-rule score breakdown and rejection reasons (BRIEF §6.2). Powers
         *     the ranker-tuning view; still never exposes NZB URLs.
         */
        DebugSearchResponse: {
            results: components["schemas"]["DebugWorkDto"][] | null;
            indexers: components["schemas"]["IndexerDiagnosticDto"][] | null;
        };
        DebugWorkDto: {
            workId: string | null;
            mediaType: string | null;
            title: string | null;
            /** Format: int32 */
            year?: number | null;
            /** Format: int32 */
            tmdbId?: number | null;
            imdbId?: string | null;
            /** Format: int32 */
            runtimeMinutes?: number | null;
            /** Format: int32 */
            season?: number | null;
            /** Format: int32 */
            episode?: number | null;
            releases: components["schemas"]["DebugReleaseDto"][] | null;
        };
        ErrorDetail: {
            code: string | null;
            message: string | null;
        };
        /** @description Typed error envelope rendered consistently by every endpoint. */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** @description POST /api/v1/events body (BRIEF §6.2). */
        EventRequest: {
            releaseId: string | null;
            workId?: string | null;
            /** @description "start" | "progress" | "stop". */
            event: string | null;
            /** Format: int64 */
            positionTicks?: number | null;
            /** @description Originating front-end ("jellyfin" | "web" | …). */
            source?: string | null;
        };
        /** @description General config as returned by the config API — the TMDB key is masked. */
        GeneralConfigResponse: {
            tmdbApiKey?: string | null;
            hasTmdbApiKey?: boolean;
            /** Format: int32 */
            sessionTtlSeconds?: number;
            /** Format: int32 */
            searchCacheTtlSeconds?: number;
            /** Format: int32 */
            segmentCacheSizeMb?: number;
            /** Format: int32 */
            connectionBudget?: number;
        };
        /** @description Write model for general config. Secret Streamarr.Server.Config.GeneralConfigWrite.TmdbApiKey is write-only. */
        GeneralConfigWrite: {
            tmdbApiKey?: string | null;
            /** Format: int32 */
            sessionTtlSeconds?: number | null;
            /** Format: int32 */
            searchCacheTtlSeconds?: number | null;
            /** Format: int32 */
            segmentCacheSizeMb?: number | null;
            /** Format: int32 */
            connectionBudget?: number | null;
        };
        HealthResponse: {
            status: string | null;
            version: string | null;
            indexers?: components["schemas"]["ReachabilityStatus"][] | null;
            providers?: components["schemas"]["ReachabilityStatus"][] | null;
        };
        /** @description Per-indexer fan-out diagnostics for the debug view. */
        IndexerDiagnosticDto: {
            indexerId: string | null;
            indexerName: string | null;
            status: string | null;
            /** Format: int32 */
            itemCount?: number;
            /** Format: double */
            elapsedMs?: number;
            error?: string | null;
        };
        /** @description Indexer as returned by the config API — the API key is masked, never plaintext. */
        IndexerResponse: {
            id: string | null;
            name: string | null;
            baseUrl: string | null;
            apiKey?: string | null;
            hasApiKey?: boolean;
            categories?: number[] | null;
            enabled?: boolean;
            /** Format: int32 */
            priority?: number;
        };
        /** @description Outcome of an indexer connectivity test (BRIEF §6.2 /config/indexers/{id}/test). */
        IndexerTestResult: {
            success: boolean;
            /** Format: double */
            latencyMs: number;
            serverTitle?: string | null;
            serverVersion?: string | null;
            /** Format: int32 */
            categoryCount?: number;
            searchAvailable?: boolean;
            movieSearchAvailable?: boolean;
            tvSearchAvailable?: boolean;
            error?: string | null;
        };
        /** @description Write model for indexer create/update. Secret Streamarr.Server.Config.IndexerWrite.ApiKey is write-only. */
        IndexerWrite: {
            id?: string | null;
            name: string | null;
            baseUrl: string | null;
            apiKey?: string | null;
            categories?: number[] | null;
            enabled?: boolean | null;
            /** Format: int32 */
            priority?: number | null;
        };
        /** @description Body of POST /api/v1/auth/login (BRIEF §6.4). */
        LoginRequest: {
            username?: string | null;
            password?: string | null;
        };
        /** @description A minted admin session token and its lifetime. */
        LoginResponse: {
            token: string | null;
            tokenType?: string | null;
            /** Format: int32 */
            expiresInSeconds: number;
            /** Format: date-time */
            expiresAt: string;
            username: string | null;
            role: string | null;
        };
        /** @description Identity of the caller behind the current bearer token (GET /api/v1/auth/me). */
        MeResponse: {
            name: string | null;
            role: string | null;
        };
        /**
         * @description Neutral media stream shape — deliberately NOT Jellyfin's MediaStream schema
         *     (BRIEF §6.2): the plugin maps this onto Jellyfin's model, other front-ends
         *     consume it as-is.
         */
        MediaStreamInfo: {
            /** @description "Video", "Audio" or "Subtitle". */
            type: string | null;
            codec?: string | null;
            /** Format: int32 */
            width?: number | null;
            /** Format: int32 */
            height?: number | null;
            /** Format: int32 */
            channels?: number | null;
            language?: string | null;
        };
        /** @description The raw parser output for a release (BRIEF §7.1), surfaced for tuning. */
        ParsedFieldsDto: {
            title?: string | null;
            /** Format: int32 */
            year?: number | null;
            mediaType: string | null;
            resolution?: string | null;
            source?: string | null;
            videoCodec?: string | null;
            hdr?: string | null;
            audioCodec?: string | null;
            audioChannels?: string | null;
            atmos?: boolean;
            edition?: string | null;
            releaseGroup?: string | null;
            proper?: boolean;
            repack?: boolean;
            languages?: string[] | null;
            /** Format: int32 */
            season?: number | null;
            episodes?: number[] | null;
            absoluteEpisodes?: number[] | null;
            seasonPack?: boolean;
            airDate?: string | null;
        };
        /** @description Provider as returned by the config API — the password is masked, never plaintext. */
        ProviderResponse: {
            id: string | null;
            name: string | null;
            host: string | null;
            /** Format: int32 */
            port?: number;
            useSsl?: boolean;
            username?: string | null;
            password?: string | null;
            hasPassword?: boolean;
            /** Format: int32 */
            maxConnections?: number;
            /** Format: int32 */
            priority?: number;
            enabled?: boolean;
            isBackupOnly?: boolean;
        };
        /** @description Outcome of a provider connectivity test (BRIEF §6.2 /config/providers/{id}/test). */
        ProviderTestResult: {
            /** @description True when at least one authenticated connection was established. */
            success: boolean;
            /**
             * Format: int32
             * @description How many simultaneous authenticated connections we could open (≤ MaxConnections).
             */
            achievableConnections: number;
            /** Format: int32 */
            requestedConnections: number;
            error?: string | null;
        };
        /** @description Write model for provider create/update. Secret Streamarr.Server.Config.ProviderWrite.Password is write-only. */
        ProviderWrite: {
            id?: string | null;
            name: string | null;
            host: string | null;
            /** Format: int32 */
            port?: number | null;
            useSsl?: boolean | null;
            username?: string | null;
            password?: string | null;
            /** Format: int32 */
            maxConnections?: number | null;
            /** Format: int32 */
            priority?: number | null;
            enabled?: boolean | null;
            isBackupOnly?: boolean | null;
        };
        /** @description Parsed quality attributes of a release (BRIEF §6.2 / §7.1). */
        QualityDto: {
            resolution?: string | null;
            source?: string | null;
            codec?: string | null;
            hdr?: string | null;
            audio?: string | null;
            edition?: string | null;
            proper?: boolean;
            repack?: boolean;
        };
        QualityProfile: {
            id?: string | null;
            name?: string | null;
            preferredResolutions?: string[] | null;
            preferredSources?: string[] | null;
            preferredCodecs?: string[] | null;
            preferredLanguages?: string[] | null;
            groupAllowList?: string[] | null;
            groupDenyList?: string[] | null;
            /** Format: int32 */
            resolutionWeight?: number;
            /** Format: int32 */
            sourceWeight?: number;
            /** Format: int32 */
            codecWeight?: number;
            /** Format: int32 */
            languageWeight?: number;
            /** Format: int32 */
            audioWeight?: number;
            /** Format: int32 */
            sizeWeight?: number;
            /** Format: int32 */
            properRepackBonus?: number;
            /** Format: int32 */
            recencyBonus?: number;
            /** Format: int32 */
            grabsBonus?: number;
            /** Format: int32 */
            groupAllowBonus?: number;
            /** Format: int32 */
            groupDenyPenalty?: number;
            /** Format: int64 */
            minBytesPerMinute?: number;
            /** Format: int64 */
            maxBytesPerMinute?: number;
            sizeBands?: {
                [key: string]: components["schemas"]["SizeBand"];
            } | null;
            isDefault?: boolean;
        };
        ReachabilityStatus: {
            name: string | null;
            reachable: boolean;
            /** Format: double */
            latencyMs?: number | null;
            error?: string | null;
        };
        /** @description A machine-readable rejection reason (BRIEF §7.2). */
        RejectionDto: {
            code: string | null;
            message: string | null;
        };
        /**
         * @description A ranked release as surfaced by `/search`. The NZB URL and indexer API key are
         *     never present here — they stay server-side (BRIEF §6.2).
         */
        ReleaseDto: {
            releaseId: string | null;
            title: string | null;
            indexer: string | null;
            /** Format: int64 */
            sizeBytes?: number;
            quality: components["schemas"]["QualityDto"];
            languages?: string[] | null;
            releaseGroup?: string | null;
            /** Format: int32 */
            ageDays?: number;
            /** Format: int32 */
            grabs?: number;
            /** Format: int32 */
            score?: number;
            rejected?: boolean;
            rejectionReasons?: string[] | null;
            /** @description "unknown" | "ready" | "degraded" | "dead" (known only after a resolve). */
            health: string | null;
        };
        /** @description Request body of POST /api/v1/resolve (BRIEF §6.2). */
        ResolveRequest: {
            releaseId: string | null;
            /** @description Originating front-end ("jellyfin", "web", …) for session attribution. */
            client?: string | null;
        };
        /** @description Response of POST /api/v1/resolve — the exact shape from BRIEF §6.2. */
        ResolveResponse: {
            releaseId: string | null;
            /** @description "ready" | "degraded" | "dead". */
            status: string | null;
            /** @description Absolute stream URL; null when the release is dead. */
            streamUrl?: string | null;
            container?: string | null;
            /** Format: int64 */
            sizeBytes?: number | null;
            /** Format: int64 */
            runTimeTicks?: number | null;
            mediaStreams?: components["schemas"]["MediaStreamInfo"][] | null;
            /** Format: int32 */
            sessionTtlSeconds?: number;
            /** @description Next-best release of the same work, set when this one is dead. */
            suggestedFallbackReleaseId?: string | null;
        };
        /** @description One line of the score breakdown (BRIEF §7.3): a rule and its point value. */
        ScoreLineDto: {
            rule: string | null;
            /** Format: int32 */
            points: number;
        };
        /** @description Response of GET /api/v1/search — the exact shape from BRIEF §6.2. */
        SearchResponse: {
            results: components["schemas"]["WorkDto"][] | null;
        };
        /** @description One live session as listed by GET /api/v1/sessions. */
        SessionResponse: {
            token: string | null;
            releaseId: string | null;
            workId: string | null;
            state: string | null;
            container?: string | null;
            /** Format: int64 */
            sizeBytes?: number;
            /** Format: int64 */
            bytesServed?: number;
            /** Format: int32 */
            nntpConnectionsInFlight?: number;
            /** Format: int64 */
            nntpCommandsTotal?: number;
            client?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            lastAccessedAt?: string;
            /** Format: date-time */
            expiresAt?: string;
        };
        SizeBand: {
            /** Format: int64 */
            minBytesPerMinute: number;
            /** Format: int64 */
            maxBytesPerMinute: number;
        };
        /** @description One aggregated work with its ranked releases (BRIEF §6.2 / §7.4). */
        WorkDto: {
            workId: string | null;
            /** @description "movie" or "tv". */
            mediaType: string | null;
            title: string | null;
            /** Format: int32 */
            year?: number | null;
            /** Format: int32 */
            tmdbId?: number | null;
            imdbId?: string | null;
            overview?: string | null;
            posterUrl?: string | null;
            backdropUrl?: string | null;
            /** Format: int32 */
            runtimeMinutes?: number | null;
            /**
             * Format: int32
             * @description Set for TV works.
             */
            season?: number | null;
            /** Format: int32 */
            episode?: number | null;
            releases: components["schemas"]["ReleaseDto"][] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
