// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Streamarr.Server.Persistence;

#nullable disable

namespace Streamarr.Server.Persistence.Migrations
{
    [DbContext(typeof(StreamarrDbContext))]
    [Migration("20260720152635_AddArtworkBadgeSetting")]
    partial class AddArtworkBadgeSetting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.28");

            modelBuilder.Entity("Streamarr.Server.Persistence.Entities.ApiKeyEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("Streamarr.Server.Persistence.Entities.CachedReleaseEntity", b =>
                {
                    b.Property<string>("ReleaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CacheFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CachedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FileCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("HitCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Indexer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastAccessedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("MediaProbeCachedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaProbeJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaProbeKey")
                        .HasColumnType("TEXT");

                    b.Property<long>("NzbSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReleaseRegistrationJson")
                        .HasColumnType("TEXT");

                    b.Property<long>("ReleaseSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SegmentCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ReleaseId");

                    b.HasIndex("LastAccessedAt");

                    b.ToTable("CachedReleases");
                });

            modelBuilder.Entity("Streamarr.Server.Persistence.Entities.GeneralConfigEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AddStreamarrBadge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConnectionBudget")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JwtSigningKeyEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<int>("SearchCacheTtlSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SegmentCacheSizeMb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionTtlSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TmdbApiKeyEncrypted")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GeneralConfig");
                });

            modelBuilder.Entity("Streamarr.Server.Persistence.Entities.IndexerEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedDownloadHosts")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKeyEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Indexers");
                });

            modelBuilder.Entity("Streamarr.Server.Persistence.Entities.NotificationConfigEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppTokenEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<string>("Device")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmergencyExpireSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmergencyRetrySeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ErrorCooldownSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ErrorPriority")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeDeviceName")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeReleaseId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeUserName")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonitorIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyApplicationStarted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyErrors")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyOutages")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyPlaybackProgress")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyPlaybackStarted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyPlaybackStopped")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyRecoveries")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyResolveFailed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyResolveSucceeded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OutageFailureThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OutagePriority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OutageReminderMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProgressIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecoveryPriority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sound")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsagePriority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserKeyEncrypted")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NotificationConfig");
                });

            modelBuilder.Entity("Streamarr.Server.Persistence.Entities.ProfileEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Streamarr.Server.Persistence.Entities.ProviderEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBackupOnly")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxConnections")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseSsl")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("Streamarr.Server.Persistence.Entities.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Streamarr.Server.Persistence.Entities.WatchEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalUserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaybackSessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PositionTicks")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlaybackSessionId");

                    b.HasIndex("ReceivedAt");

                    b.HasIndex("ReleaseId");

                    b.ToTable("WatchEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
