// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Streamarr.Server.Persistence;

#nullable disable

namespace Streamarr.Server.Persistence.Migrations
{
    [DbContext(typeof(StreamarrDbContext))]
    [Migration("20261001003047_AddReleaseContainers")]
    partial class AddReleaseContainers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.30");

            modelBuilder.Entity("Streamarr.Server.Persistence.Entities.AdminRefreshSessionEntity", b =>
                {
                    b.Property<string>("TokenHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplacementTokenEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TokenHash");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("UserId");

                    b.ToTable("AdminRefreshSessions");
                });

            modelBuilder.Entity("Streamarr.Server.Persistence.Entities.ApiKeyEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("Streamarr.Server.Persistence.Entities.ArtworkPaletteEntity", b =>
                {
                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<long>("ComputedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tint")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tint2")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("ImageUrl");

                    b.ToTable("ArtworkPalettes");
                });

            modelBuilder.Entity("Streamarr.Server.Persistence.Entities.CachedReleaseEntity", b =>
                {
                    b.Property<string>("ReleaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CacheFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CachedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FileCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("HitCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Indexer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastAccessedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("MediaProbeCachedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaProbeJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaProbeKey")
                        .HasColumnType("TEXT");

                    b.Property<long>("NzbSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReleaseRegistrationJson")
                        .HasColumnType("TEXT");

                    b.Property<long>("ReleaseSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SegmentCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ReleaseId");

                    b.HasIndex("LastAccessedAt");

                    b.ToTable("CachedReleases");
                });

            modelBuilder.Entity("Streamarr.Server.Persistence.Entities.CatalogSpecSummaryEntity", b =>
                {
                    b.Property<string>("WorkId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Audio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hdr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resolution")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VideoCodec")
                        .HasColumnType("TEXT");

                    b.HasKey("WorkId");

                    b.ToTable("CatalogSpecSummaries");
                });

            modelBuilder.Entity("Streamarr.Server.Persistence.Entities.GeneralConfigEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AddReleaseScoreToName")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AddStreamarrBadge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConnectionBudget")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EphemeralCacheSizeMb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IndexerResultLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JwtSigningKeyEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<int>("SearchCacheTtlSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SegmentCacheSizeMb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionTtlSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TmdbApiKeyEncrypted")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GeneralConfig");
                });

            modelBuilder.Entity("Streamarr.Server.Persistence.Entities.IndexerEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedDownloadHosts")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKeyEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Indexers");
                });

            modelBuilder.Entity("Streamarr.Server.Persistence.Entities.NotificationConfigEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppTokenEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<string>("Device")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmergencyExpireSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmergencyRetrySeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ErrorCooldownSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ErrorPriority")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeDeviceName")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeReleaseId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeUserName")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonitorIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyApplicationStarted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyErrors")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyOutages")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyPlaybackProgress")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyPlaybackStarted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyPlaybackStopped")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyRecoveries")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyResolveFailed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyResolveSucceeded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OutageFailureThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OutagePriority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OutageReminderMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProgressIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecoveryPriority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sound")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsagePriority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserKeyEncrypted")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NotificationConfig");
                });

            modelBuilder.Entity("Streamarr.Server.Persistence.Entities.PlaybackRangeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalUserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastReleaseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSessionToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaybackSessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PositionTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RangesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScopeKey")
                        .IsUnique();

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("WorkId");

                    b.ToTable("PlaybackRanges");
                });

            modelBuilder.Entity("Streamarr.Server.Persistence.Entities.PreDownloadConfigEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentFileThresholdSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DownloadCurrentFile")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DownloadNextEpisode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxConcurrentDownloads")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NextEpisodeReleaseSimilarityThresholdPercent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NextEpisodeThresholdPercent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PreferSimilarNextEpisodeRelease")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PreDownloadConfig");
                });

            modelBuilder.Entity("Streamarr.Server.Persistence.Entities.ProfileEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Streamarr.Server.Persistence.Entities.ProviderEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBackupOnly")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxConnections")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseSsl")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("Streamarr.Server.Persistence.Entities.ReleaseContainerEntity", b =>
                {
                    b.Property<string>("ReleaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LastUsedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReleaseId");

                    b.HasIndex("LastUsedAt");

                    b.ToTable("ReleaseContainers");
                });

            modelBuilder.Entity("Streamarr.Server.Persistence.Entities.StreamEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DurationMs")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("StartMs")
                        .HasColumnType("REAL");

                    b.Property<long>("StreamRecordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StreamRecordId");

                    b.ToTable("StreamEvents");
                });

            modelBuilder.Entity("Streamarr.Server.Persistence.Entities.StreamRecordEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttemptId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("BytesServed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Client")
                        .HasColumnType("TEXT");

                    b.Property<string>("CloseReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Container")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalState")
                        .HasColumnType("TEXT");

                    b.Property<long>("NntpCommandsTotal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReleaseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedByName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedReleaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedTitle")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("TimelineStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FinalState");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("StreamRecords");
                });

            modelBuilder.Entity("Streamarr.Server.Persistence.Entities.TranscodingConfigEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TranscodingConfig");
                });

            modelBuilder.Entity("Streamarr.Server.Persistence.Entities.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Streamarr.Server.Persistence.Entities.ViewerConfigEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpPasswordEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ViewerConfig");
                });

            modelBuilder.Entity("Streamarr.Server.Persistence.Entities.ViewerEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowTranscoding")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BlockUnrated")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<long?>("EmailVerifiedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastLoginAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LockoutEndsAt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxAge")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxConcurrentStreams")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("PasswordChangedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PendingEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("PendingTotpSecretEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<long?>("TotpEnabledAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TotpLastUsedStep")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TotpSecretEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.ToTable("Viewers");
                });

            modelBuilder.Entity("Streamarr.Server.Persistence.Entities.ViewerOneTimeCodeEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ConsumedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .HasColumnType("TEXT");

                    b.Property<string>("ViewerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ViewerId", "Purpose");

                    b.ToTable("ViewerOneTimeCodes");
                });

            modelBuilder.Entity("Streamarr.Server.Persistence.Entities.ViewerRecoveryCodeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UsedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ViewerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ViewerId");

                    b.ToTable("ViewerRecoveryCodes");
                });

            modelBuilder.Entity("Streamarr.Server.Persistence.Entities.ViewerSessionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("AccessExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessTokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CookieMode")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastSeenAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreviousRefreshTokenHash")
                        .HasColumnType("TEXT");

                    b.Property<long>("RefreshExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("RevokedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RevokedReason")
                        .HasColumnType("TEXT");

                    b.Property<long?>("RotatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RotatedTokensEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<string>("ViewerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccessTokenHash")
                        .IsUnique();

                    b.HasIndex("PreviousRefreshTokenHash");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique();

                    b.HasIndex("ViewerId");

                    b.ToTable("ViewerSessions");
                });

            modelBuilder.Entity("Streamarr.Server.Persistence.Entities.ViewerWatchStateEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountedPlaybackId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DurationTicks")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastPlaybackId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastPlayedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastReleaseId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Played")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PlayedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PositionTicks")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeriesWorkId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ViewerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ViewerId", "LastPlayedAt");

                    b.HasIndex("ViewerId", "SeriesWorkId");

                    b.HasIndex("ViewerId", "WorkId")
                        .IsUnique();

                    b.ToTable("ViewerWatchStates");
                });

            modelBuilder.Entity("Streamarr.Server.Persistence.Entities.WatchEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalUserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaybackSessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PositionTicks")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlaybackSessionId");

                    b.HasIndex("ReceivedAt");

                    b.HasIndex("ReleaseId");

                    b.ToTable("WatchEvents");
                });

            modelBuilder.Entity("Streamarr.Server.Persistence.Entities.StreamEventEntity", b =>
                {
                    b.HasOne("Streamarr.Server.Persistence.Entities.StreamRecordEntity", null)
                        .WithMany("Events")
                        .HasForeignKey("StreamRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Streamarr.Server.Persistence.Entities.ViewerOneTimeCodeEntity", b =>
                {
                    b.HasOne("Streamarr.Server.Persistence.Entities.ViewerEntity", null)
                        .WithMany()
                        .HasForeignKey("ViewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Streamarr.Server.Persistence.Entities.ViewerRecoveryCodeEntity", b =>
                {
                    b.HasOne("Streamarr.Server.Persistence.Entities.ViewerEntity", null)
                        .WithMany()
                        .HasForeignKey("ViewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Streamarr.Server.Persistence.Entities.ViewerSessionEntity", b =>
                {
                    b.HasOne("Streamarr.Server.Persistence.Entities.ViewerEntity", null)
                        .WithMany()
                        .HasForeignKey("ViewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Streamarr.Server.Persistence.Entities.ViewerWatchStateEntity", b =>
                {
                    b.HasOne("Streamarr.Server.Persistence.Entities.ViewerEntity", null)
                        .WithMany()
                        .HasForeignKey("ViewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Streamarr.Server.Persistence.Entities.StreamRecordEntity", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
