using System.Collections.Concurrent;
using System.Diagnostics;
using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

namespace Streamarr.DevWorld;

public sealed record ProbeStream
{
    public int Index { get; init; }
    public string CodecType { get; init; } = string.Empty;
    public string CodecName { get; init; } = string.Empty;
    public string? Profile { get; init; }
    public string? PixFmt { get; init; }
    public int? Width { get; init; }
    public int? Height { get; init; }
    public string? ColorTransfer { get; init; }
    public string? ColorPrimaries { get; init; }
    public int? Channels { get; init; }
    public string? ChannelLayout { get; init; }
    public string? Language { get; init; }
    public string? Title { get; init; }
    public bool Default { get; init; }
    public bool Forced { get; init; }
}

public sealed record MediaProbe
{
    public string FormatName { get; init; } = string.Empty;
    public double DurationSeconds { get; init; }
    public List<ProbeStream> Streams { get; init; } = [];
}

public sealed record GeneratedMedia(string Path, long SizeBytes, MediaProbe Probe, bool Reused);

/// <summary>Generates each planned file once into the shared cache (temp + rename, per-file lock) and ffprobe-verifies it.</summary>
public sealed class MediaGenerator(DevWorldOptions options, Action<string> log)
{
    /// <summary>Bump when the generated bytes change so stale cache entries are not reused.</summary>
    public const int GeneratorVersion = 2;

    private const string MasterDisplay = "G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(10000000,50)";

    private static readonly TimeSpan LockTimeout = TimeSpan.FromMinutes(30);
    private static readonly TimeSpan UnusedMediaRetention = TimeSpan.FromDays(30);

    public async Task<IReadOnlyDictionary<string, GeneratedMedia>> EnsureAsync(IReadOnlyList<PlannedMedia> plan, CancellationToken ct)
    {
        Directory.CreateDirectory(options.MediaDir);
        Directory.CreateDirectory(Path.Combine(options.MediaDir, ".tmp"));
        Directory.CreateDirectory(Path.Combine(options.MediaDir, ".locks"));

        var results = new ConcurrentDictionary<string, GeneratedMedia>(StringComparer.Ordinal);
        var ordered = plan.OrderByDescending(Cost).ToList();
        await Parallel.ForEachAsync(
            ordered,
            new ParallelOptions { MaxDegreeOfParallelism = options.GenerateJobs, CancellationToken = ct },
            async (media, token) => results[media.Key] = await EnsureOneAsync(media, token));
        PruneStale(results.Values.Select(m => Path.GetFileName(m.Path)).ToHashSet(StringComparer.Ordinal));
        return results;
    }

    /// <summary>Drops media no plan has used for 30 days (every boot touches its probe sidecars) and orphaned temp files.</summary>
    private void PruneStale(IReadOnlySet<string> inUse)
    {
        var now = DateTime.UtcNow;
        foreach (var probe in Directory.EnumerateFiles(options.MediaDir, "*.probe.json"))
        {
            var fileName = Path.GetFileName(probe)[..^".probe.json".Length];
            if (inUse.Contains(fileName) || now - File.GetLastWriteTimeUtc(probe) < UnusedMediaRetention)
                continue;
            TryDelete(Path.Combine(options.MediaDir, fileName));
            TryDelete(probe);
            TryDelete(Path.Combine(options.MediaDir, ".locks", fileName + ".lock"));
            log($"pruned {fileName} (unused for {UnusedMediaRetention.TotalDays:0} days)");
        }

        foreach (var tmp in Directory.EnumerateFiles(Path.Combine(options.MediaDir, ".tmp")))
        {
            if (now - File.GetLastWriteTimeUtc(tmp) > TimeSpan.FromDays(1))
                TryDelete(tmp);
        }

        static void TryDelete(string path)
        {
            try { File.Delete(path); } catch (IOException) { } catch (UnauthorizedAccessException) { }
        }
    }

    private static double Cost(PlannedMedia media)
        => media.DurationSeconds * media.Variant.Video.Width * media.Variant.Video.Height
           * (media.Variant.Video.Codec == "hevc" ? 4 : 1);

    public static string FileNameFor(PlannedMedia media)
    {
        var identity = JsonSerializer.Serialize(new
        {
            GeneratorVersion,
            media.VariantId,
            media.Variant,
            media.BurnTitle,
            media.BurnLabel,
            media.DurationSeconds,
            media.Fps,
            media.AccentColor,
        }, DevCatalog.Json);
        var hash = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(identity)))[..12].ToLowerInvariant();
        return $"{media.Key}-{hash}.{media.Extension}";
    }

    private async Task<GeneratedMedia> EnsureOneAsync(PlannedMedia media, CancellationToken ct)
    {
        var fileName = FileNameFor(media);
        var finalPath = Path.Combine(options.MediaDir, fileName);
        var probePath = finalPath + ".probe.json";

        if (File.Exists(finalPath) && File.Exists(probePath))
        {
            TouchQuietly(probePath);
            return new GeneratedMedia(finalPath, new FileInfo(finalPath).Length, LoadProbe(probePath), Reused: true);
        }

        await using var fileLock = await AcquireLockAsync(Path.Combine(options.MediaDir, ".locks", fileName + ".lock"), fileName, ct);
        var reused = File.Exists(finalPath);
        if (!reused)
        {
            var tmpPath = Path.Combine(options.MediaDir, ".tmp", $"{Guid.NewGuid():N}.{media.Extension}");
            try
            {
                var sw = Stopwatch.StartNew();
                await GenerateAsync(media, tmpPath, ct);
                Verify(media, await ProbeAsync(tmpPath, ct));
                File.Move(tmpPath, finalPath, overwrite: false);
                log($"generated {fileName} ({new FileInfo(finalPath).Length / 1024.0 / 1024.0:0.0} MB) in {sw.Elapsed.TotalSeconds:0.0}s");
            }
            finally
            {
                if (File.Exists(tmpPath))
                    File.Delete(tmpPath);
            }
        }

        var probe = await ProbeAsync(finalPath, ct);
        Verify(media, probe);
        var tmpProbe = probePath + $".{Guid.NewGuid():N}.tmp";
        await File.WriteAllTextAsync(tmpProbe, JsonSerializer.Serialize(probe, DevCatalog.Json), ct);
        File.Move(tmpProbe, probePath, overwrite: true);
        return new GeneratedMedia(finalPath, new FileInfo(finalPath).Length, probe, reused);
    }

    private static MediaProbe LoadProbe(string path)
        => JsonSerializer.Deserialize<MediaProbe>(File.ReadAllText(path), DevCatalog.Json)
           ?? throw new InvalidDataException($"Unreadable probe sidecar {path}");

    private static void TouchQuietly(string path)
    {
        try { File.SetLastWriteTimeUtc(path, DateTime.UtcNow); } catch (IOException) { } catch (UnauthorizedAccessException) { }
    }

    private async Task<FileStream> AcquireLockAsync(string path, string fileName, CancellationToken ct)
    {
        var waited = Stopwatch.StartNew();
        var announced = false;
        while (true)
        {
            try
            {
                return new FileStream(path, FileMode.OpenOrCreate, FileAccess.ReadWrite, FileShare.None);
            }
            catch (IOException e) when (e is not (DirectoryNotFoundException or PathTooLongException))
            {
                if (waited.Elapsed > LockTimeout)
                    throw new TimeoutException($"Gave up after {LockTimeout.TotalMinutes:0} min waiting for {path}: {e.Message}", e);
                if (!announced)
                    log($"waiting for {fileName}: another process holds its lock (generating it?)");
                announced = true;
                await Task.Delay(500, ct);
            }
        }
    }

    private async Task GenerateAsync(PlannedMedia media, string outPath, CancellationToken ct)
    {
        var v = media.Variant;
        var width = v.Video.Width;
        var height = v.Video.Height;
        var duration = media.DurationSeconds;
        var fps = media.Fps;
        var gop = (int)Math.Round(2 * FpsValue(fps));
        var workDir = Directory.CreateTempSubdirectory("devworld-gen-").FullName;
        try
        {
            var args = new List<string> { "-hide_banner", "-loglevel", "error", "-nostats", "-y" };
            args.AddRange(["-f", "lavfi", "-i", $"testsrc2=s={Even(width / 3)}x{Even(height / 3)}:r={fps}:d={duration}"]);
            var panelHeight = BitmapFont.PanelHeight(width);
            args.AddRange(["-f", "rawvideo", "-pix_fmt", "gray", "-s", $"{width}x{panelHeight}", "-framerate", "1", "-i", "pipe:0"]);
            for (var i = 0; i < v.Audio.Count; i++)
                args.AddRange(["-f", "lavfi", "-i", AudioSource(v.Audio[i], duration)]);
            for (var j = 0; j < v.Subtitles.Count; j++)
            {
                var sub = v.Subtitles[j];
                var subPath = Path.Combine(workDir, $"sub{j}.{sub.Format}");
                await File.WriteAllTextAsync(subPath, sub.Format == "ass" ? Ass(sub, duration) : Srt(sub, duration), new UTF8Encoding(false), ct);
                args.AddRange(["-i", subPath]);
            }

            var pixFmt = v.Video.BitDepth == 10 ? "yuv420p10le" : "yuv420p";
            var accent = media.AccentColor.TrimStart('#');
            args.AddRange([
                "-filter_complex",
                $"[0:v]scale={width}:{height}:flags=fast_bilinear,drawbox=x=iw-iw/32:y=0:w=iw/32:h=ih:color=0x{accent}:t=fill,setsar=1[bg];" +
                $"[1:v]format=yuv420p[panel];[bg][panel]overlay=x=0:y=H-h:eof_action=repeat,format={pixFmt}[v]",
                "-map", "[v]",
            ]);
            for (var i = 0; i < v.Audio.Count; i++)
                args.AddRange(["-map", $"{2 + i}:a"]);
            for (var j = 0; j < v.Subtitles.Count; j++)
                args.AddRange(["-map", $"{2 + v.Audio.Count + j}:s"]);

            args.AddRange(VideoArgs(v, gop, fps));
            for (var i = 0; i < v.Audio.Count; i++)
                args.AddRange(AudioArgs(v.Audio[i], i, v.Audio.Count));
            for (var j = 0; j < v.Subtitles.Count; j++)
                args.AddRange(SubtitleArgs(v.Subtitles[j], j));
            if (v.Audio.Any(a => a.Codec is "dts" or "truehd"))
                args.AddRange(["-strict", "-2"]);

            args.AddRange(["-metadata", $"title={media.BurnTitle} [{media.BurnLabel}]", "-t", duration.ToString(CultureInfo.InvariantCulture)]);
            args.AddRange(v.Container switch
            {
                "mp4" => ["-movflags", "+faststart", "-f", "mp4"],
                "mpg" => ["-f", "dvd"],
                _ => ["-f", "matroska"],
            });
            args.Add(outPath);

            var psi = new ProcessStartInfo("ffmpeg")
            {
                RedirectStandardInput = true,
                RedirectStandardError = true,
                RedirectStandardOutput = true,
                UseShellExecute = false,
            };
            foreach (var arg in args)
                psi.ArgumentList.Add(arg);

            using var process = Process.Start(psi) ?? throw new InvalidOperationException("Could not start ffmpeg (is it on PATH?).");
            var stderr = process.StandardError.ReadToEndAsync(ct);
            _ = process.StandardOutput.ReadToEndAsync(ct);
            try
            {
                await WritePanelsAsync(process.StandardInput.BaseStream, media, width, panelHeight, ct);
            }
            catch (IOException)
            {
                // ffmpeg exited early; its stderr explains why.
            }
            finally
            {
                try { process.StandardInput.Close(); } catch (IOException) { }
            }

            await process.WaitForExitAsync(ct);
            if (process.ExitCode != 0)
                throw new InvalidOperationException($"ffmpeg failed for {media.Key} ({process.ExitCode}): {await stderr}");
        }
        finally
        {
            try { Directory.Delete(workDir, recursive: true); } catch (IOException) { }
        }
    }

    private static async Task WritePanelsAsync(Stream stdin, PlannedMedia media, int width, int panelHeight, CancellationToken ct)
    {
        var frame = new byte[width * panelHeight];
        var title = BitmapFont.Sanitize(media.BurnTitle);
        var label = BitmapFont.Sanitize(media.BurnLabel);
        var level = media.Variant.Video.Hdr is null ? (byte)235 : (byte)150;
        var duration = TimeSpan.FromSeconds(media.DurationSeconds);
        for (var second = 0; second <= media.DurationSeconds; second++)
        {
            BitmapFont.RenderPanel(frame, width, title, label, TimeSpan.FromSeconds(second), duration, level);
            await stdin.WriteAsync(frame, ct);
        }

        await stdin.FlushAsync(ct);
    }

    private static IEnumerable<string> VideoArgs(VariantSpec v, int gop, string fps)
    {
        var k = v.Video.Kbps;
        switch (v.Video.Codec)
        {
            case "h264":
                return
                [
                    "-c:v", "libx264", "-preset", "veryfast", "-profile:v", "high", "-crf", "23",
                    "-maxrate", $"{k}k", "-bufsize", $"{2 * k}k", "-g", $"{gop}", "-keyint_min", $"{gop}",
                    "-sc_threshold", "0", .. v.Container == "mp4" ? (string[])["-tag:v", "avc1"] : [],
                ];
            case "hevc":
                var hdr = v.Video.Hdr == "hdr10"
                    ? $":hdr10=1:hdr10-opt=1:colorprim=bt2020:transfer=smpte2084:colormatrix=bt2020nc:range=limited:master-display={MasterDisplay}:max-cll=1000,400"
                    : string.Empty;
                return
                [
                    "-c:v", "libx265", "-preset", "ultrafast", "-profile:v", v.Video.BitDepth == 10 ? "main10" : "main",
                    "-x265-params",
                    $"log-level=error:keyint={gop}:min-keyint={gop}:scenecut=0:crf=24:vbv-maxrate={k}:vbv-bufsize={2 * k}:repeat-headers=1{hdr}",
                    .. v.Video.Hdr == "hdr10"
                        ? (string[])["-color_primaries", "bt2020", "-color_trc", "smpte2084", "-colorspace", "bt2020nc", "-color_range", "tv"]
                        : [],
                    .. v.Container == "mp4" ? (string[])["-tag:v", "hvc1"] : [],
                ];
            case "av1":
                return ["-c:v", "libsvtav1", "-preset", "10", "-crf", "38", "-g", $"{gop}", "-svtav1-params", $"mbr={k}"];
            case "mpeg2video":
                return
                [
                    "-c:v", "mpeg2video", "-b:v", $"{k}k", "-maxrate", $"{k * 3 / 2}k", "-bufsize", "1835k",
                    "-g", FpsValue(fps) > 26 ? "15" : "12", "-bf", "2", "-aspect", v.Video.Aspect ?? "16:9",
                ];
            default:
                throw new InvalidDataException($"Unsupported video codec {v.Video.Codec}");
        }
    }

    private static IEnumerable<string> AudioArgs(AudioSpec a, int i, int count)
    {
        var args = new List<string>();
        switch (a.Codec)
        {
            case "aac" or "eac3" or "ac3":
                args.AddRange([$"-c:a:{i}", a.Codec, $"-b:a:{i}", $"{a.Kbps ?? 192}k"]);
                break;
            case "dts":
                args.AddRange([$"-c:a:{i}", "dca", $"-b:a:{i}", "768k"]);
                break;
            case "truehd":
                args.AddRange([$"-c:a:{i}", "truehd", $"-sample_fmt:a:{i}", "s16p"]);
                break;
            case "opus":
                args.AddRange([$"-c:a:{i}", "libopus", $"-b:a:{i}", $"{a.Kbps ?? 128}k"]);
                if (a.Channels > 2)
                    args.AddRange([$"-mapping_family:a:{i}", "1"]);
                break;
            default:
                throw new InvalidDataException($"Unsupported audio codec {a.Codec}");
        }

        var isDefault = a.Default || (i == 0 && count == 1);
        args.AddRange([
            $"-ar:a:{i}", "48000",
            $"-metadata:s:a:{i}", $"language={a.Language}",
            $"-metadata:s:a:{i}", $"title={a.Title}",
            $"-disposition:a:{i}", isDefault ? "default" : "0",
        ]);
        return args;
    }

    private static IEnumerable<string> SubtitleArgs(SubtitleSpec s, int j) =>
    [
        $"-c:s:{j}", s.Format == "ass" ? "ass" : "srt",
        $"-metadata:s:s:{j}", $"language={s.Language}",
        $"-metadata:s:s:{j}", $"title={s.Title}",
        $"-disposition:s:{j}", s.Forced ? "forced" : "0",
    ];

    /// <summary>Short per-channel beeps (distinct pitch and offset per channel) so channel mapping is audible.</summary>
    private static string AudioSource(AudioSpec a, int duration)
    {
        var baseHz = a.Language == "ger" ? 330.0 : 440.0;
        var layout = a.Channels switch { 1 => "mono", 2 => "stereo", 6 => "5.1", 8 => "7.1", _ => throw new InvalidDataException($"{a.Channels} channels") };
        var exprs = Enumerable.Range(0, a.Channels).Select(k =>
        {
            var hz = a.Channels >= 6 && k == 3 ? 80 : baseHz * (1 + 0.25 * k);
            var offset = (0.12 * k).ToString("0.00", CultureInfo.InvariantCulture);
            return $"0.3*sin(2*PI*{hz.ToString("0.#", CultureInfo.InvariantCulture)}*t)*lt(mod(t-{offset}\\,1)\\,0.1)";
        });
        return $"aevalsrc=exprs={string.Join('|', exprs)}:s=48000:c={layout}:d={duration}";
    }

    private static string Srt(SubtitleSpec s, int duration)
    {
        var sb = new StringBuilder();
        var n = 0;
        foreach (var (start, text) in Cues(s, duration))
        {
            n++;
            sb.Append(n).Append('\n')
              .Append(SrtTime(start)).Append(" --> ").Append(SrtTime(start + 4)).Append('\n')
              .Append(text).Append("\n\n");
        }

        return sb.ToString();
    }

    private static string Ass(SubtitleSpec s, int duration)
    {
        var sb = new StringBuilder();
        sb.Append("[Script Info]\nScriptType: v4.00+\nPlayResX: 1920\nPlayResY: 1080\nWrapStyle: 0\nScaledBorderAndShadow: yes\n\n");
        sb.Append("[V4+ Styles]\nFormat: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n");
        sb.Append("Style: Default,Arial,64,&H00FFFFFF,&H000000FF,&H00000000,&H80000000,0,0,0,0,100,100,0,0,1,3,1,2,40,40,160,1\n");
        sb.Append("Style: Sign,Arial,56,&H0000FFFF,&H000000FF,&H00202020,&H80000000,-1,0,0,0,100,100,0,0,1,2,0,8,40,40,70,1\n");
        sb.Append("Style: Whisper,Arial,52,&H00FFC080,&H000000FF,&H00000000,&H80000000,0,-1,0,0,100,100,0,0,1,2,1,2,40,40,160,1\n\n");
        sb.Append("[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n");
        var i = 0;
        foreach (var (start, text) in Cues(s, duration))
        {
            var style = (i++ % 3) switch { 0 => "Default", 1 => "Whisper", _ => "Sign" };
            var styled = style == "Default" ? $"{{\\b1}}{text}{{\\b0}} {{\\c&H00FF00&}}*" : text;
            sb.Append($"Dialogue: 0,{AssTime(start)},{AssTime(start + 4)},{style},,0,0,0,,{styled}\n");
        }

        return sb.ToString();
    }

    private static IEnumerable<(int Start, string Text)> Cues(SubtitleSpec s, int duration)
    {
        var german = s.Language == "ger";
        if (s.Forced)
        {
            for (var t = Math.Min(15, duration / 3); t + 4 < duration; t += 60)
                yield return (t, german ? $"[DE FORCED] Schild: \"Ausgang\" ({Tc(t)})" : $"[EN FORCED] Sign: \"Exit\" ({Tc(t)})");
            yield break;
        }

        var n = 0;
        for (var t = Math.Min(2, duration / 4); t + 4 < duration; t += 10)
        {
            n++;
            yield return (t, german ? $"[DE] Untertitel {n} bei {Tc(t)} - Grüße, Straße" : $"[EN] Subtitle {n} at {Tc(t)}");
        }
    }

    private static string Tc(int seconds) => TimeSpan.FromSeconds(seconds).ToString(@"hh\:mm\:ss", CultureInfo.InvariantCulture);

    private static string SrtTime(int seconds) => TimeSpan.FromSeconds(seconds).ToString(@"hh\:mm\:ss\,fff", CultureInfo.InvariantCulture);

    private static string AssTime(int seconds) => $"{seconds / 3600}:{seconds / 60 % 60:00}:{seconds % 60:00}.00";

    private static int Even(int value) => value / 2 * 2;

    public static double FpsValue(string fps)
    {
        var parts = fps.Split('/');
        return parts.Length == 2
            ? double.Parse(parts[0], CultureInfo.InvariantCulture) / double.Parse(parts[1], CultureInfo.InvariantCulture)
            : double.Parse(fps, CultureInfo.InvariantCulture);
    }

    public static async Task<MediaProbe> ProbeAsync(string path, CancellationToken ct)
    {
        var psi = new ProcessStartInfo("ffprobe")
        {
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
        };
        foreach (var arg in (string[])["-v", "error", "-print_format", "json", "-show_format", "-show_streams", path])
            psi.ArgumentList.Add(arg);
        using var process = Process.Start(psi) ?? throw new InvalidOperationException("Could not start ffprobe.");
        var stdout = process.StandardOutput.ReadToEndAsync(ct);
        var stderr = process.StandardError.ReadToEndAsync(ct);
        await process.WaitForExitAsync(ct);
        if (process.ExitCode != 0)
            throw new InvalidOperationException($"ffprobe failed for {path}: {await stderr}");

        using var doc = JsonDocument.Parse(await stdout);
        var root = doc.RootElement;
        var format = root.GetProperty("format");
        return new MediaProbe
        {
            FormatName = Str(format, "format_name") ?? string.Empty,
            DurationSeconds = double.TryParse(Str(format, "duration"), CultureInfo.InvariantCulture, out var d) ? d : 0,
            Streams = root.GetProperty("streams").EnumerateArray().Select(s =>
            {
                var tags = s.TryGetProperty("tags", out var t) ? t : default;
                var disposition = s.TryGetProperty("disposition", out var di) ? di : default;
                return new ProbeStream
                {
                    Index = s.GetProperty("index").GetInt32(),
                    CodecType = Str(s, "codec_type") ?? string.Empty,
                    CodecName = Str(s, "codec_name") ?? string.Empty,
                    Profile = Str(s, "profile"),
                    PixFmt = Str(s, "pix_fmt"),
                    Width = Int(s, "width"),
                    Height = Int(s, "height"),
                    ColorTransfer = Str(s, "color_transfer"),
                    ColorPrimaries = Str(s, "color_primaries"),
                    Channels = Int(s, "channels"),
                    ChannelLayout = Str(s, "channel_layout"),
                    Language = tags.ValueKind == JsonValueKind.Object ? Str(tags, "language") : null,
                    Title = tags.ValueKind == JsonValueKind.Object ? Str(tags, "title") : null,
                    Default = disposition.ValueKind == JsonValueKind.Object && Int(disposition, "default") == 1,
                    Forced = disposition.ValueKind == JsonValueKind.Object && Int(disposition, "forced") == 1,
                };
            }).ToList(),
        };

        static string? Str(JsonElement e, string name)
            => e.TryGetProperty(name, out var v) ? v.ValueKind == JsonValueKind.String ? v.GetString() : v.ToString() : null;

        static int? Int(JsonElement e, string name)
            => e.TryGetProperty(name, out var v) && v.ValueKind == JsonValueKind.Number ? v.GetInt32() : null;
    }

    /// <summary>Fails when the generated file is not what the variant (and therefore the release name) claims.</summary>
    public static void Verify(PlannedMedia media, MediaProbe probe)
    {
        var v = media.Variant;
        var problems = new List<string>();
        var video = probe.Streams.Where(s => s.CodecType == "video").ToList();
        var audio = probe.Streams.Where(s => s.CodecType == "audio").ToList();
        var subs = probe.Streams.Where(s => s.CodecType == "subtitle").ToList();

        if (video.Count != 1 || video[0].CodecName != v.Video.Codec)
            problems.Add($"video codec {string.Join(",", video.Select(s => s.CodecName))} != {v.Video.Codec}");
        else
        {
            if (video[0].Width != v.Video.Width || video[0].Height != v.Video.Height)
                problems.Add($"video size {video[0].Width}x{video[0].Height} != {v.Video.Width}x{v.Video.Height}");
            if ((v.Video.BitDepth == 10) != (video[0].PixFmt?.Contains("10", StringComparison.Ordinal) == true))
                problems.Add($"pixel format {video[0].PixFmt} does not match {v.Video.BitDepth}-bit");
            if (v.Video.Hdr == "hdr10" && (video[0].ColorTransfer != "smpte2084" || video[0].ColorPrimaries != "bt2020"))
                problems.Add($"HDR10 needs PQ + BT.2020, got {video[0].ColorTransfer}/{video[0].ColorPrimaries}");
        }

        if (audio.Count != v.Audio.Count)
            problems.Add($"{audio.Count} audio streams != {v.Audio.Count}");
        else
        {
            for (var i = 0; i < audio.Count; i++)
            {
                if (audio[i].CodecName != v.Audio[i].Codec || audio[i].Channels != v.Audio[i].Channels)
                    problems.Add($"audio {i}: {audio[i].CodecName}/{audio[i].Channels}ch != {v.Audio[i].Codec}/{v.Audio[i].Channels}ch");
                if (v.Container != "mpg" && audio[i].Language != v.Audio[i].Language)
                    problems.Add($"audio {i}: language {audio[i].Language} != {v.Audio[i].Language}");
            }
        }

        if (subs.Count != v.Subtitles.Count)
            problems.Add($"{subs.Count} subtitle streams != {v.Subtitles.Count}");
        else
        {
            for (var j = 0; j < subs.Count; j++)
            {
                var want = v.Subtitles[j].Format == "ass" ? "ass" : "subrip";
                if (subs[j].CodecName != want || subs[j].Forced != v.Subtitles[j].Forced || subs[j].Language != v.Subtitles[j].Language)
                    problems.Add($"subtitle {j}: {subs[j].CodecName}/{subs[j].Language}/forced={subs[j].Forced} != {want}/{v.Subtitles[j].Language}/forced={v.Subtitles[j].Forced}");
            }
        }

        if (Math.Abs(probe.DurationSeconds - media.DurationSeconds) > 2)
            problems.Add($"duration {probe.DurationSeconds:0.0}s != {media.DurationSeconds}s");

        if (problems.Count > 0)
            throw new InvalidDataException($"Generated media {media.Key} does not match its variant: {string.Join("; ", problems)}");
    }
}
